### ISSUE TITLE
图标更换后显示异常

### ISSUE THREAD

**Issue by isyinxian** [jackhanyuan/hexo-theme-new-yilia#10]
![image](https://github.com/jackhanyuan/hexo-theme-new-yilia/assets/85432589/45c0115b-4f82-45e5-9063-50da3d48e0fe)
![image](https://github.com/jackhanyuan/hexo-theme-new-yilia/assets/85432589/345f4c3d-dd40-4889-8487-d8909fd5132a)

关于博主说的page的样式问题，我开始觉得是还没刷新，后面发现可能还是hexo的问题，哪个没部署问题，然后我又本地想测试一下，结果本地直接崩了，然后我又删掉重新配置了一遍，然后这次头像会显示，但是站标不显示，暂时不知道什么问题，环境都是最新的，然后又重新发布一遍github，page还没更新，不过仓库是重新配的，在本地是如图显示的，问题也比较奇怪，博主呃，就当特殊情况吧

**Comment by isyinxian** [comment]
我重新部署了一遍，等了大概一天，github page是有样式了，但是图片是时而有时而没有，现在也是不知道什么情况，环境全部是最新的，安装流程也是一步步来的，异常就是刚装完有图片，但是过了一天再去看就又没了，可能我是这个例情况吧，按道理说，刚开始本地能正常显示，应该就不会有问题了，但是本地都不显示了，所以github page的只能那样啦
https://isyinxian.github.io/blog/

**Comment by isyinxian** [comment]
> 我重新部署了一遍，等了大概一天，github page是有样式了，但是图片是时而有时而没有，现在也是不知道什么情况，环境全部是最新的，安装流程也是一步步来的，异常就是刚装完有图片，但是过了一天再去看就又没了，可能我是这个例情况吧，按道理说，刚开始本地能正常显示，应该就不会有问题了，但是本地都不显示了，所以github page的只能那样啦 https://isyinxian.github.io/blog/

我试着检查了一下，只有当自己在地址栏输入图片的地址，才能访问，但是主页打开是not fund错误
![image](https://github.com/jackhanyuan/hexo-theme-new-yilia/assets/85432589/8f83fa8b-6388-44da-b3fe-aaa856db525a)
![image](https://github.com/jackhanyuan/hexo-theme-new-yilia/assets/85432589/52befd2b-8b4b-40a5-8df9-b7c32a1348eb)

**Comment by jackhanyuan** [comment]
应该是config中url及root配置存在问题，_config.yml 中url应该为https://isyinxian.github.io/blog/  themes/new-yilia/_config.yml 中root应该为/blog/

**Comment by isyinxian** [comment]
> 应该是config中url及root配置存在问题，_config.yml 中url应该为https://isyinxian.github.io/blog/ themes/new-yilia/_config.yml 中root应该为/blog/

我觉得不是，我一开始就是按照注释url中添加了/blog，在theme中/后面也都加上了blog/

**Comment by jackhanyuan** [comment]
稍等，代码有bug，之前只考虑了根目录部署`/`的情况，你这种子目录部署的url还存在bug，我尽快解决。

**Comment by isyinxian** [comment]
> 稍等，代码有bug，之前只考虑了根目录部署`/`的情况，你这种子目录部署的url还存在bug，我尽快解决。
> 
> 如果着急的话，建议根目录部署，github仓库名改为`isyinxian.github.io`即可根目录部署。

哦，嗯，不急不急，我也是边学习，边踩坑，边分享，如果可以的话，你在解决的地方加上注释，或者说改动的url的地方加上说明，方便查看源码，我也试着看看源码，学习学习

**Comment by jackhanyuan** [comment]
@isyinxian 路径bug已经修复，可以重新下载部署，注意配置文件有变化。

查看代码变化看这里https://github.com/jackhanyuan/hexo-theme-new-yilia/commit/b7208052a7f2bb7f57d2a07654fd12ed149a5702

**Comment by isyinxian** [comment]
> @isyinxian 路径bug已经修复，可以重新下载部署，注意配置文件有变化。
> 
> 查看代码变化看这里[b720805](https://githubfast.com/jackhanyuan/hexo-theme-new-yilia/commit/b7208052a7f2bb7f57d2a07654fd12ed149a5702)

已重新部署，头像可正常显示，基本上可以了，除了显示比较慢一点，https://isyinxian.github.io/blog/
但是所发表的文章，展开全文只能跳转到我留的你的new-yilia那篇文章，也就是跳转页面异常

**Comment by jackhanyuan** [comment]
@isyinxian github.io访问本来就慢一些，对速度有要求的话可以上cdn。文章跳转问题我测试了，没发现问题，应该是你哪里没弄对，我刚才推送了最新版本，建议`hexo cl`完全清理后重新部署。

**Comment by jackhanyuan** [comment]
@isyinxian 我看了一下，你的post里只有一篇文章，tag里有好几篇，应该就是你没清理干净，建议hexo cl完全清理后重新部署。另外每篇文章的`abbrlink`应该是不一样的，你的所有文章都跳转一篇，我怀疑abbrlink都是一样的，你可以删除文章中的`abbrlink`字段让其自动生成。

**Comment by isyinxian** [comment]
> @isyinxian 我看了一下，你的post里只有一篇文章，tag里有好几篇，应该就是你没清理干净，建议hexo cl完全清理后重新部署。另外每篇文章的`abbrlink`应该是不一样的，你的所有文章都跳转一篇，我怀疑abbrlink都是一样的，你可以删除文章中的`abbrlink`字段让其自动生成。

![image](https://github.com/jackhanyuan/hexo-theme-new-yilia/assets/85432589/9f40e63b-8e9e-4fec-9ee0-f4ca2830745f)
感谢，已解决，展开链接异常，就是文章头部的链接编号，设成了一样的，需要在代码块输入前，赋值0，然后再发布就回生成随机页面
