### ISSUE TITLE
hexo g 有个报错

### ISSUE THREAD

**Issue by aeronxie** [jackhanyuan/hexo-theme-new-yilia#2]
![WX20230325-212717@2x](https://user-images.githubusercontent.com/9351800/227720062-9872c6ef-0784-402b-b964-df0fd505e944.png)

不知道是不是版本问题，原 yilia 没问题

**Comment by jackhanyuan** [comment]
不要在原yilia基础上升级，会有冲突，请按照[README](https://github.com/jackhanyuan/hexo-theme-new-yilia/blob/main/README.md)全新操作，我刚才复现了，没有问题，hexo:版本6.3.0。
