### ISSUE TITLE
w文章太长，截断按钮文字 # excerpt_link: 'more'

### ISSUE THREAD

**Issue by longsizhuo123** [jackhanyuan/hexo-theme-new-yilia#7]
在new_yilia\_config.yml 中的参数：
```
# 文章太长，截断按钮文字
# excerpt_link: 'more'
```
是否是当文章字数过多的时候，截断部分文章呢？请问该如何使用呢。
我尝试了
```
excerpt_link: 'more'
excerpt_length: 100
```
或者是在文章中加入`<!---more--->`来控制，但是都没有效果

**Comment by jackhanyuan** [comment]
new-yilia的`_config.yml`中# excerpt_link: 'more'可以不用，只需要在文中需要截断的地方加入`<!--more-->`即可，你的截断符格式有误

**Comment by longsizhuo123** [comment]
可以询问一下这个是靠什么方法实现的吗🥲

**Comment by longsizhuo123** [comment]
可以在`_config.yml`中加入`excerpt_length: 100`来批量处理吗

**Comment by jackhanyuan** [comment]
> 可以询问一下这个是靠什么方法实现的吗🥲
hexo原生支持的，详见https://hexo.io/docs/tag-plugins#Post-Excerpt

**Comment by jackhanyuan** [comment]
> 可以在`_config.yml`中加入`excerpt_length: 100`来批量处理吗

目前主题不支持，欢迎PR

**Comment by longsizhuo** [comment]
了解，谢谢！
