### ISSUE TITLE
添加自己的图片后不显示bug

### ISSUE THREAD

**Issue by isyinxian** [jackhanyuan/hexo-theme-new-yilia#9]
![image](https://github.com/jackhanyuan/hexo-theme-new-yilia/assets/85432589/faf1d534-a80f-4fbc-80be-31c3a06ae827)
![image](https://github.com/jackhanyuan/hexo-theme-new-yilia/assets/85432589/1a4ace3c-2aa2-46cd-960d-09944d5c3d3a)

不知道博主还在不在更新，因为在yilia那边也是遇到这样的问题，然后看到了博主更新的new-yilia，然后也是clone下来了，然后本地部署，发现了一个问题：就是添加了头像和地址栏图标之后本地访问头像不显示，然后我部署到github page 的也是不显示，如果博主还在维护的话，知道是什么问题的话还请不吝赐教

**Comment by jackhanyuan** [comment]
我这边测试没有这bug，请确保按照[README](https://github.com/jackhanyuan/hexo-theme-new-yilia/blob/main/README.md)教程安装本主题，然后将图片放置`hexo-theme-new-yilia\themes\new-yilia\source\img`路径下，并修改配置文件`hexo-theme-new-yilia\themes\new-yilia\_config.yml`中`avatar: '/img/your_avatar.png'`和`favicon: '/img/favicon.ico'`。

**Comment by isyinxian** [comment]
> 我这边测试没有这bug，请确保按照[README](https://githubfast.com/jackhanyuan/hexo-theme-new-yilia/blob/main/README.md)教程安装本主题，然后将图片放置`hexo-theme-new-yilia\themes\new-yilia\source\img`路径下，并修改配置文件`hexo-theme-new-yilia\themes\new-yilia\_config.yml`中`avatar: '/img/your_avatar.png'`和`favicon: '/img/favicon.ico'`。

![image](https://github.com/jackhanyuan/hexo-theme-new-yilia/assets/85432589/e9c2b4a3-0425-4607-9a57-4c140f185935)
是这样的，我是按照教程去部署的，然后我用自己喜欢的头像替换掉了默认的图片，但是其他的都没有变，然后图片都不会显示了，我并没有更改图片路径，就是博主的打赏的图片也没有显示了

**Comment by jackhanyuan** [comment]
应该是你其它操作导致了异常，无法解决的话建议从新开始操作一次，并清除浏览器缓存。
我这边尝试没有问题
![image](https://github.com/jackhanyuan/hexo-theme-new-yilia/assets/24978318/dda32e6b-c664-45da-b774-4d3b6933d1e1)

**Comment by jackhanyuan** [comment]
我这边测试环境是：
OS：Windows 11
npm 版本：10.2.0
Hexo版本：6.3.0

**Comment by isyinxian** [comment]
> 我这边测试环境是： OS：Windows 11 npm 版本：10.2.0 Hexo版本：6.3.0

现以解决，不过不知道具体原因，唯一做的是我把hexo，npm，node更新到最新版本，然后现在发布到了page上
https://isyinxian.github.io/blog/

**Comment by jackhanyuan** [comment]
好的，你的博客部署可能还存在问题，我这边访问只显示文字，样式都显示不了
